# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_intercept <- function(Z_orig, K, Phi_moe, R, lambda, d) {
    .Call('_harmony_get_intercept', PACKAGE = 'harmony', Z_orig, K, Phi_moe, R, lambda, d)
}

compute_Y <- function(Z_cos, R) {
    .Call('_harmony_compute_Y', PACKAGE = 'harmony', Z_cos, R)
}

scaleRows_dgc <- function(x, p, i, ncol, nrow, thresh) {
    .Call('_harmony_scaleRows_dgc', PACKAGE = 'harmony', x, p, i, ncol, nrow, thresh)
}

